# Generated by Django 3.2.16 on 2022-12-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('price', models.IntegerField(verbose_name='Precio')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='projects/', verbose_name='Imagen')),
                ('publicationsDate', models.DateTimeField(verbose_name='Fecha de publicacion')),
            ],
        ),
    ]
